# Generated by Django 2.2.1 on 2020-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=264, unique=True)),
                ('short_url', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
